### ISSUE TITLE
Add new snapshot date for upcoming release of SCE-R

### ISSUE THREAD

**Issue by falgreen** [NovoNordisk-OpenSource/r.workflows#1]

**Comment by akselthomsen** [comment]
@falgreen is this issue still relevant?
we are currently checking:

```yaml
      config:
          - date: 2023-10-25
            r: 4.3.1
          - date: 2024-08-06
            r: 4.4.1
```
